### PR TITLE
Fix bug making it impossible to fetch 0 values from hmap keys

### PR DESCRIPTION
**Pull request by jslang**

### CODE REVIEW

**Comment by jslang** [comment]
I didn't see a way to run tests, is there any documentation for the proper way to run tests for this project?

**Comment by honzajavorek** [comment]
@jslang Hi, thank you for the PR! Standard way to run tests is `python setup.py test`. Travis did it for you, indeed.

I don't have time (motivation) currently to maintain `redis-collections` much (not even for PR reviews, which is pretty sad) and I'm looking for a maintainer. It wouldn't be much hassle as there are just minor bugs with existing PRs and the only major feature is Python 3 support and it also has a PR in progress. If you feel like taking over this library, it would be much appreciated.

**Comment by jslang** [comment]
I see. I'm submitting this on behalf of a project that we use at udemy.com, so perhaps I can convince someone there to take over. I won't be with the company much longer so not sure if I'll be utilizing this lib myself in the near future.

I'll get back to you if I find someone to take over.

**Comment by bbayles** [comment]
@jslang, the issue fixed in this PR should have been fixed by the merge of #29. I'll publish a release with that in it shortly. Thanks!

**Pull request closed without merging**
