### PR TITLE
Add support for using redislite if the module is installed.

### PR DESCRIPTION
**Pull request by dwighthubbard**
This adds support for using the redislite module so a separate redis server does not have to be installed.

Also added a tox.ini file to allow running unit tests on multiple python interpreters locally and getting code coverage reports.

### CODE REVIEW

**Comment by honzajavorek** [comment]
Thanks! :+1: I hope I'll get to review this soon, looks like a lot of nice work added :)

**Comment by dwighthubbard** [comment]
Two comments:

1. I can redo this pull request without the future changes.  I didn't see the pull request to add python3 support that already exists.
2. Would it make sense to switch the travis configuration to use tox for testing like redislite does.  This makes it easy to run the test suite against multiple configurations locally and makes it possible to add additional environments to the tox configuration to do things like PEP8/PyLinit/Sphinx Docs generation.

**Comment by honzajavorek** [comment]
@dwighthubbard 

The Py3 support isn't finished and I have lack of time to do that. I wanted to have a small hackaton for myself or some of my friends to add Py3 support and resolve other issues, but I'm just terrible in getting to do it. Update of TravisCI to have Py3 support would be part of that.

Tox definitely makes sense to me.

--------

Looking at your large contributions, would you mind to consider to join me as maintainer on this repo? I think `redis-collections` suffer from me being part of way too many activities and efforts.

**Comment by dwighthubbard** [comment]
I'd be happy to help as a maintainer but like you have a lot of stuff going on.

**Comment by honzajavorek** [comment]
@dwighthubbard I'm sorry for not responding. I don't have time (motivation) currently to maintain `redis-collections` much (not even for PR reviews, which is pretty sad) and as I mentioned earlier, I'm looking for a maintainer. It wouldn't be much hassle as there are just minor bugs with existing PRs and the only major feature is Python 3 support and it also has this PR in progress. If you still feel like taking over this library, it would be much appreciated. Are you still interested? I'd add you to collaborators.

**Comment by bbayles** [comment]
@dwighthubbard, I'm inclined to close this PR. Correct me if I'm wrong, but from my testing it is possible to use `redislite` without adding specific support for it:

```python
>>> from redislite import StrictRedis
... from redis_collections import Dict, List, Set
... 
... D = Dict(redis=StrictRedis())
... D['key'] = 'value'
... 
... L = List(redis=StrictRedis())
... L.append('item')
... 
... S = Set(redis=StrictRedis())
... S.add('item')
```

This is certainly not as good as being able to use it without having to pass in an object, but for now I think it's an appropriate level of support.

I may revisit this after making some larger changes for Python 3.

Thanks!

**Pull request closed without merging**
